---
# tasks file for ucsdlib.epel

- name: Add EPEL Key
  rpm_key:
    key: '{{ epel_gpg[ansible_distribution_major_version] }}'
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install EPEL RPM
  package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  when: ansible_os_family == 'RedHat'
