# -*- mode: ruby -*-
# vi: set ft=ruby :

# This follows the .travis.yml file.
# In places where they differ, .travis.yml is canonical

Vagrant.configure(2) do |config|
  role_name = "ansible-role-epel"
  #config.vm.box = "ubuntu/precise64"
  config.vm.box = "centos/7"
  config.vm.synced_folder "..", "/home/vagrant/#{role_name}", type: "rsync"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "setup.yml"
    ansible.extra_vars = {
      role_name: "#{role_name}"
    }
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Vagrant Specific Setup
    cd "/home/vagrant/#{role_name}"

    #install
    ansible --version

    #script
    ansible-playbook tests/test.yml -i tests/inventory --syntax-check
    ansible-playbook tests/test.yml -i tests/inventory --check
    ansible-playbook tests/test.yml -i tests/inventory
    ansible-playbook tests/test.yml -i tests/inventory --check
    ansible-playbook tests/test.yml -i tests/inventory
  SHELL
end
